# Generated by Django 5.0.4 on 2024-09-02 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
