# Generated by Django 5.0.4 on 2024-09-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
